# Generated by Django 4.2.30 on 2026-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_review_clinic_cleanliness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
